version: '3.7'

services:
  ui:
    container_name: simple-http-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    # volumes:
    #   - '/app/node_modules' #this creates a cache on your local disk of the node_modules folders, to help speed up future work
      # - './ui:/app'
    ports:
      - '80:80'
      - '443:443'
    environment:
      - NODE_ENV=dev
      - PORT=80
  api:
    container_name: simple-api
    build:
      context: ./api
      dockerfile: Dockerfile
    # volumes:
      # - '/app/node_modules' #this creates a cache on your local disk of the node_modules folders, to help speed up future work
    ports:
      - '3002:3002'
      - '9229:9229' #for node debugging
    environment:
      - NODE_ENV=dev
      - PORT=3002
      # - CHOKIDAR_USEPOLLING=true

